### ISSUE TITLE
sum_basic may has an error

### ISSUE THREAD

**Issue by guojiangwei2** [miso-belica/sumy#101]
line 108-109 in file`sum_basic.py`, sentences_as_words only compute once, while iteration the index of the best sentence is still the index of raw document sentences, but the `sentences_list` has been updated, so it will get the wrong index for the target sentence. maybe the sentences_as_words needs to be poped too.

**Comment by miso-belica** [comment]
Hope, you closed this because you found out that I am doing it at line 115 https://github.com/miso-belica/sumy/blob/726e6c3a4b9fc8cbf8a29019a7b4c7500221005e/sumy/summarizers/sum_basic.py#L115 :)

**Comment by guojiangwei2** [comment]
yes, I found that line, thanks for answering. By the way, thanks for your awesome work.
