### ISSUE TITLE
breadability parse html documents is not stable

### ISSUE THREAD

**Issue by guojiangwei2** [miso-belica/sumy#103]
I found that `breadablility` is not stable for picking target contents. related question link is posted [here](https://github.com/bookieio/breadability/issues/32), can you give me any suggestion a new library for the same purpose in python or fix `breadablilty`.

**Comment by miso-belica** [comment]
Hi, as you correctly pointed out you have some problem with breadability library. Then why this duplicate issue in sumy? Is there anything wrong with sumy?

I don't know the better library. In times when I was searching for some I have picked bradability and enhanced it a little. I maintain also [jusText](https://github.com/miso-belica/jusText) which I tried to enhance but I think it's for different purpose, but you can try it if you think it suits your need. Both breadability and jusText have list of [alternatives](https://github.com/bookieio/breadability#alternatives) I tried so you can test also them.

Or, and I like that the most, you can try to fix breadability and send PR if you think here is some issue :)

**Comment by guojiangwei2** [comment]
I comment [some lines](https://github.com/guojiangwei2/breadability/commit/a383c56c34131915189ce8a26db668846c5e4c51) in `breadblility` and fix the problem I mentioned before, but I don't confirm that I do the right thing, any comments will be appreciated, thx.

**Comment by guojiangwei2** [comment]
thx for your comments, since `sumy` use `breadablitity` to parse html content, so I linked it here for more chance to be answered.

**Comment by miso-belica** [comment]
@guojiangwei2 Great, you can do the changes and send it as PR into breadability now. You can run tests there or just send PR and TravisCI do it for you :) And would be nice if you [allow to modify the code](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests) to maintainers ;)
