### ISSUE TITLE
running with chinese text

### ISSUE THREAD

**Issue by ikelca** [miso-belica/sumy#108]
it is a great tool, I found it by googling text summarization. While I tested with some chinese webpage using sumy lex-rank --length=10 --language='chinese' --url=xxxxxxx
it did not come out any result.
also tried with LSA, not result too, 
just wondering, is this too supporting chinese ?

**Comment by miso-belica** [comment]
@ikelca Hi, jop sumy should support Chinese. Support was added in https://github.com/miso-belica/sumy/pull/93. If you can provide me full command to execute or text you are trying to sumarize I can try to find the problem, but I don't speak Chinese so maybe I find just nothing. You can try to use sumy as library and find out if problem is in parser or in summarizer.
