### ISSUE TITLE
Runtime division error in Text Rank

### ISSUE THREAD

**Issue by isarth** [miso-belica/sumy#112]
In Text rank Matrix weights are divided as :
-> weights /= weights.sum(axis=1)[:, numpy.newaxis] 
The above command causes runtime division error when row is zero

**Comment by miso-belica** [comment]
Thanks for the report. I will try check it.

**Comment by isarth** [comment]
Changing it to the following 
->  weights=weights/(numpy.sum(weights,axis=1)+epsilon )
Works fine !!

**Comment by fahadshery** [comment]
this still hasn't been resolved

**Comment by miso-belica** [comment]
Should be solved by https://github.com/miso-belica/sumy/pull/117

**Comment by SAMiddle** [comment]
So is this line now `weights /= (weights.sum(axis=1)[:, numpy.newaxis]+self._delta)` dividing each entry in the matrix by the sum of the entries in the corresponding row (adding delta to this sum)? So if the sum is zero, then the result would be 10 million.

**Comment by SAMiddle** [comment]
I am assuming that the thumbs up means that I am not extremely ignorant when it comes to understanding Python built-in functions
