### ISSUE TITLE
Register summarizer output to string variable 

### ISSUE THREAD

**Issue by racindustries** [miso-belica/sumy#113]
Hi miso, 

Using the python API I'd like to save the output of sumy summarizer to a string variable that i could analyse with ntlk, but I keep getting 'Setence' objects, which can't be used in nltk. 

Could you help me here ? 

Thanks a lot !

**Comment by miso-belica** [comment]
Hi, these objects have `__str__` defined so you can use `str(sentence)` to get text or `unicode(sentence)` on Python 2.

**Comment by miso-belica** [comment]
From the 👍 on my comment, I guess this works for you so I am going to close it here. But feel free to reopen if you need more info :)
