### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AhmedAbuRaed** [miso-belica/sumy#115]
Hi,
After running the example code I am getting `UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 579: character maps to <undefined>` when executing the following code.:
`parser= PlaintextParser.from_file(datasetPath + "/" + file, Tokenizer(LANGUAGE))` 
I uploaded one of the files to recreate the problem
[C08-1031.txt](https://github.com/miso-belica/sumy/files/2482850/C08-1031.txt)
PS: reading the file into a string works
` parser = PlaintextParser.from_string(f.read(), Tokenizer(LANGUAGE))` 
my best guess is you need to add utf8 encoding when opening the file at line 34 of plaintext.py
Thanks

**Comment by miso-belica** [comment]
Hi @AhmedAbuRaed, thanks for the report and the suggested suggestion. Sorry for the really late reply. I fixed the issue in the connected PR and plan to release the fix after checking more issues.
