### ISSUE TITLE
TextRank Too Heavy?

### ISSUE THREAD

**Issue by infosisio** [miso-belica/sumy#121]
It seems to be irrationally stressing the processor, while Lsa doesn't. What's up?

**Comment by miso-belica** [comment]
Hi @infosisio, thanks for the report. Do you have some numbers? An example document(s) and the setting you are using? And what is your PC configuration? It's hard to tell more without the info. Also, I released a new version of Sumy yesterday and TextRank algorithm is completely changed there, can you test it and let us know here?

**Comment by miso-belica** [comment]
Hi @infosisio, I recently merged some changes into the master. You can review them at https://github.com/miso-belica/sumy/pull/140 Maybe you could try Sumy with them if it's better ;)
