### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by gigatesseract** [miso-belica/sumy#124]
For testing the sumy tool, is it possible to use proxy for downloading the articles?

**Comment by miso-belica** [comment]
Hi @gigatesseract of course, you can use any tool. For example https://2.python-requests.org/en/master/user/advanced/#proxies and give to the sumy only `response.text` :)

**Comment by gigatesseract** [comment]
I tried the above in my work environment, it wasn't working. I guess the proxy settings there were messed up. It works out of my work environment, though :smile:
