### ISSUE TITLE
Tune Parameter?

### ISSUE THREAD

**Issue by Arvedek** [miso-belica/sumy#125]
May I know which params to tune in Textrank and Lexpagerank?

**Comment by miso-belica** [comment]
Hi @Arvedek, this is a really tough question. It's like to ask me which params to tune on your new PC :) I think it heavily depends on what you want to achieve and what data you are working with. I am afraid you need to experiment with this on your own.

**Comment by Arvedek** [comment]
Haha, yeah I also realize that. Thanks for the package, smooth and effective.
