### ISSUE TITLE
Stemmer not invoked for sumbasic

### ISSUE THREAD

**Issue by bdalal** [miso-belica/sumy#127]
Is there a reason, the stemmer is not being invoked in the SumBasicSummarizer?

**Comment by bdalal** [comment]
If it's been missed out, I'm happy to create a PR with the addition of stemmers to SumBasic

**Comment by miso-belica** [comment]
Hi @bdalal, seems you are right. I briefly skimmed the implementation and I can't see any stemmer there. Maybe it should be called in `_normalize_words` method but I would need more deep look to the summarizer. If you can prepare the PR I will be happy to do the review :)

**Comment by bdalal** [comment]
Created PR https://github.com/miso-belica/sumy/pull/131
