### ISSUE TITLE
Documentation Site?

### ISSUE THREAD

**Issue by syedsadiqalinaqvi** [miso-belica/sumy#132]
Hi, 

Thank you for the package. It seems to be very useful for working with Extractive Summarization methods. Considering the popularity of the package, I was expecting it to have a proper documentation site like other famous packages. It seems like currently, the README file is the only available documentation. That can't be true, right? While the README is a good place to get a gist of the functionality, the details about different classes, functions and their parameters need a separate place of their own. If it already exists, kindly point me towards it.

Thanks.

**Comment by miso-belica** [comment]
Hi @syedsadiqalinaqvi thanks for the issues. I have to admit there is nothing except for the README file. But as you said, I should dedicate really more time for all the issues and documentation. Thank you for the little push :)

Also, you are not the first one https://github.com/miso-belica/sumy/issues/55 😐

**Comment by syedsadiqalinaqvi** [comment]
Hey, @miso-belica thanks for the quick response. Really appreciate that you're taking this matter seriously. Of course, since this is an open-source project, so some responsibility does lie with the users of the project as well. Please let us know if we can help with this task.

**Comment by syedsadiqalinaqvi** [comment]
I'm going to use this comment as a list of items that need documentation. (Please let me know if you feel like that's spamming so I'll take this list someplace else.)

- Tokenizer
- Parser (PlainTextParser)
- Stemmer
- LexRankSummarizer
- Sentence (Summarizers return summary that's a collection of Sentence type objects)
- (more to come)

**Comment by syedsadiqalinaqvi** [comment]
@miso-belica  can you please give a quick and dirty example of how to use the evaluation metrics?

For example, assume that you have generated a ```summary``` from one of the summarizers. Also assume that you have a ```reference``` summary as a string or a list of sentences (whatever the current API prefers). How would you compute, let's say, rouge 1 score? I can see the use of command-line utility from README but having a hard-time in calling it via Python API. 

TIA

**Comment by miso-belica** [comment]
To be honest I never intended the evaluation to be used from API. It was CLI tool to test various methods. But the API is quite simple. All you need is in the file for the CLI.
1. [Feed the parser](https://github.com/miso-belica/sumy/blob/947178f5e9b95a29dfb3fa047f9990cdb8aac6fc/sumy/evaluation/__main__.py#L163) with your `reference`.
2. [Choose](https://github.com/miso-belica/sumy/blob/947178f5e9b95a29dfb3fa047f9990cdb8aac6fc/sumy/evaluation/__main__.py#L151) the evaluation method.
3. [Evaluate](https://github.com/miso-belica/sumy/blob/947178f5e9b95a29dfb3fa047f9990cdb8aac6fc/sumy/evaluation/__main__.py#L171) the result.

Evaluators are simple functions that take reference sentences and summarized sentences and return number. That's all.

**Comment by syedsadiqalinaqvi** [comment]
Thank you so much for the links! Really helpful!
