### ISSUE TITLE
How to extend current implementation to give more focus on specific sentences containing name entities.

### ISSUE THREAD

**Issue by TsvetanRangelov** [miso-belica/sumy#137]
I love the current project, but I was wondering if there was an easy way to boost the scores of sentences with named organizations contained in them? For my use case, I need to have the main topic company/organization mentioned in the input document also exist in the summary. I can extract the NERs fine and identify them, just not sure what the easiest way to approach boosting the scores of those words/sentences is?

**Comment by miso-belica** [comment]
Hi @TsvetanRangelov, thanks for the nice words :) I guess the one summarizer for the job would be [Edmundson](https://miso-belica.github.io/sumy/summarizators.html) where you can add `bonus_words` to the named entities to prefer the sentences with them. But I don't if it will not lead to prefer the sentences too much. I think you should try. I would love about the results though :) Let me know if it worked for you.

**Comment by TsvetanRangelov** [comment]
Thank you so much, I will report how it goes!

**Comment by TsvetanRangelov** [comment]
It doesn't seem to do that well right off the bat. I might make a branch and expose bonus_word_value as well as fix the typo "bunus_word_value" :). For my use case, if it doesn't work, I might consider some other methods like filtering sentences that do not contain Named Entities.
