### ISSUE TITLE
Calling the rouge_n gets an error

### ISSUE THREAD

**Issue by TobyVries** [miso-belica/sumy#145]
I'm trying to call the `rouge_n` function and passing two strings into it, however, that leads to me getting a `ValueError: Object in collection must be of type Sentence`. If I try to pass two Sentence objects containing the strings instead I then get this error. `TypeError: object of type 'Sentence' has no len()`. Any help is appreciated.

**Comment by miso-belica** [comment]
Hi @TobyVries I guess you already found the solution. My guess is that you provided empty sentences, but it would be nice if you provide more info so even others with the same problem can find your solution useful :)

The relevant code is at https://github.com/miso-belica/sumy/blob/516d5bd2e29d2e8d8eda37eb05c0c8670a866fb3/sumy/evaluation/rouge.py#L123

**Comment by TobyVries** [comment]
Unfortunately I wasn't able to find the solution. When creating the Sentence objects I would pass in either the reference or evaluation sentence along with a DefaultWordTokenizer object. This would then result in the TypeError where sentence has no length. Here's the code that I'm using. 

    token = DefaultWordTokenizer()
    tr_sentence = Sentence(rouge_textrank_summary, token)
    human_sentence = Sentence(rouge_human_summary_1, token)

    score = rouge_n(tr_sentence, human_sentence)

**Comment by miso-belica** [comment]
@TobyVries OK, now I see it. The problem is that the method accepts a collection of sentences, not a single sentence. You can see the usage example in the test https://github.com/miso-belica/sumy/blob/5773ea6ada1b4b51985ce9fef45b0be5dcffabcb/tests/test_evaluation/test_evaluation_rouge.py#L59-L72.

For you I this you should simply wrap the sentences into the list (or any other collection).

```python
token = DefaultWordTokenizer()
tr_sentence = Sentence(rouge_textrank_summary, token)
human_sentence = Sentence(rouge_human_summary_1, token)

score = rouge_n([tr_sentence], [human_sentence])
```

**Comment by TobyVries** [comment]
That seemed to fix the error but I also had to change 
    token = DefaultWordTokenizer()
into
    token = Tokenizer('english')
Now it seems to fully work so thank you for your help!
