### ISSUE TITLE
Need Python API for TextRank and LexRank

### ISSUE THREAD

**Issue by alkakhurana** [miso-belica/sumy#147]
Hi,

I need Python API for TextRank and LexRank algorithms implemented in your project. I have to read document from my system rather than summarizing any webpage.

Thanks

**Comment by alkakhurana** [comment]
Hi,

I need python API for TextRank and LexRank urgently (in sumy). Will it be possible for you?

Thanks in advance

**Comment by miso-belica** [comment]
Hi @alkakhurana , sorry but it is not possible for me. But I believe it is possible for you 🙂 You can find the API example in README and the documentation. I believe it is what you are searching for.

Have a nice day 🙂

**Comment by miso-belica** [comment]
Hope you found it in the README :)
