### ISSUE TITLE
Simplifying _get_best_sentences in kl.py

### ISSUE THREAD

**Issue by SAMiddle** [miso-belica/sumy#160]
Thank you first of all for your hard work. Just a couple of questions if you do not mind me asking:
- Are you aware of anyone who implemented kl.py in JAVA?
-  Is there a way of implementing "_get_best_sentences" without "SentenceInfo" and "ItemsCount"? I will appreciate it if you can explain the idea "_get_best_sentences".

My question is essentially as follows: say we have the "ratings", do we really need to call  "_get_best_sentences" to yield "the top" two sentences for instance? If so, then may I know the functionality of "_get_best_sentences"?

**Comment by miso-belica** [comment]
You can see the implementation at https://github.com/miso-belica/sumy/blob/5715e526830936d75645fd73ae54a41a870113a2/sumy/summarizers/_summarizer.py#L35-L53. The idea is to pick best sentences but return them in the order as they appear in the original text.

**Comment by SAMiddle** [comment]
Thanks for this. Thought it was something completely different

**Comment by SAMiddle** [comment]
Out of curiosity, have you got the source code which identifies whether a sentence  is a heading or not (i.e. "is_heading")?
Thanks in advance

**Comment by miso-belica** [comment]
Yes, `SentenceInfo` object has `Sentence` inside so you can get info about heading like this: `sentence_info.sentence.is_heading`.
