### ISSUE TITLE
Is it possible to get entire text from link?

### ISSUE THREAD

**Issue by aryan1107** [miso-belica/sumy#163]
For example in newspaper python library you can do article.text for getting entire text.

Any similar command for sumy?

**Comment by miso-belica** [comment]
Hi, sumy is not meant as an article parser. It's just a minor feature to ease the article summarization on the web. The algorithm is far from perfect and uses [breadability](https://github.com/bookieio/breadability). You should use the library for the text extraction as [newspaper](https://github.com/codelucas/newspaper), [justText](https://github.com/miso-belica/jusText) or alternatives in its readme.

But if you really want you can do this to get the full article from the parser: `" ".join(map(str, parser.document.sentences))`.
