### ISSUE TITLE
`KeyError` in `SumBasicSummarizer`

### ISSUE THREAD

**Issue by dennlinger** [miso-belica/sumy#165]
Hey, first of all, thanks for the great library!

I just encountered a bug with the `SumBasicSummarizer`, where it seems that the method looks up the document frequency of a stemmed word. However, the actual `word_freq_in_doc` dictionary only stores the frequencies for **unstemmed** words.

In particular, I believe that the culprit is the different normalization of content words between [`_get_content_words_in_sentence()`](https://github.com/miso-belica/sumy/blob/main/sumy/summarizers/sum_basic.py#L35-L39) versus the normalization in [`_get_all_content_words_in_doc()`](https://github.com/miso-belica/sumy/blob/main/sumy/summarizers/sum_basic.py#L57-L61). In particular, the former method performs stemming, whereas the latter does not.

I would have proposed a PR myself, but I don't know which is the "more correct" fix (IMO, consistent stemming should be the way to go?).

FWIW, I used this with German texts, although capitalization etc. seems to be no issue here.

**Comment by miso-belica** [comment]
Thank you for the report and the detailed analysis 🙂
