### ISSUE TITLE
IDF Calculation in lex_rank

### ISSUE THREAD

**Issue by JulianGriggs** [miso-belica/sumy#17]
In lex_rank.py, what is the motivation for calculating IDF for a word, w, as: 
IDF(w) = N/k 
where 
N = total number of sentences in the document 
k = the number of sentences containing the word

It is my understanding that:
IDF(w) = log (D/k)
where 
D = the number of documents in the corpus
k = the number of documents containing w.  

Are you treating each sentence as its own document?  If so, shouldn't there be a log thrown in front?  
I love this project by the way, thank you so much!

**Comment by lastlegion** [comment]
https://github.com/miso-belica/sumy/pull/23 Pull request

**Comment by miso-belica** [comment]
Fixed in b509a3c07350e6a4a8b63fff39a90dea7c6be4e8
