### ISSUE TITLE
"cannot import name 'Sequence' from 'collections'" error with Python 3.10

### ISSUE THREAD

**Issue by kburchfiel** [miso-belica/sumy#172]
I'm currently using Python 3.10.4. When I try to run:

`from sumy.parsers.plaintext import PlaintextParser`

I receive the following error:

`ImportError: cannot import name 'Sequence' from 'collections'`

Is there a way to resolve this, or will I need to wait for sumy to be updated?

**Comment by miso-belica** [comment]
Hi, thank you. Yes, it seems it is duplicate of #170 and I should release a new version with the fix 🙂

**Comment by miso-belica** [comment]
Should be working now if you run `pip install -U sumy` 🙂 It's fixed in version 0.10.0+
