### ISSUE TITLE
Empty stem on stemmers/greek.py

### ISSUE THREAD

**Issue by NC0DER** [miso-belica/sumy#173]
Greetings,

I found a bug regarding the greek stemmer package, while using sumy on greek texts. For certain words that are not found in its dictionary, it returns an empty stem, which makes the statement in line 33 to yield a string index out of range exception.
Therefore, line 33 in [stemmers/greek.py](https://github.com/miso-belica/sumy/blob/main/sumy/nlp/stemmers/greek.py#L34) should have an extra check for the empty string case thus becoming:
```python
if stemmed and stemmed[-1].upper() in _CONSONANTS:
```

Should I open a pull request for this issue or would you like to integrate it?

Thank you for your time.

**Comment by miso-belica** [comment]
Thank you for the report again. If u have time and mood please open a PR. But please write the test first to reproduce the bug 🙂
