### ISSUE TITLE
Limitation of length input 

### ISSUE THREAD

**Issue by phamkhactu** [miso-belica/sumy#174]
I appreciate your repo, but I have read the document but I don't know the input limit of the model. For example LuhnSummarizer model, How many words is the highest capacity? Thank in advance!

**Comment by miso-belica** [comment]
Hi, what do you mean by text capacity? There is no limit for input text in the library.

**Comment by phamkhactu** [comment]
@miso-belica thank you for your reply. It's a wonderful repo.
