### ISSUE TITLE
Ability to access UserWarnings

### ISSUE THREAD

**Issue by mrx23dot** [miso-belica/sumy#177]
After sentence is summarised I would like to access any warnings e.g:

C:\py38_64\lib\site-packages\sumy\summarizers\lsa.py:76: UserWarning: Number of words (14) is lower than 
number of sentences (15). LSA algorithm may not work properly.

so I would just keep the original sentence segment instead.

**Comment by miso-belica** [comment]
https://docs.python.org/3/library/warnings.html#warnings.catch_warnings
