### ISSUE TITLE
Summarising books by verbs

### ISSUE THREAD

**Issue by mrx23dot** [miso-belica/sumy#179]
Not really an issue, just a question.

So I'm summarising books by paragraphs, and I was thinking to get the main plot 'happening' it would be beneficial to prioratise sentences with verbs. 

I can collect every verb for a given language. As I see only Edmundson is capable taking hint words.
Not sure what stop-words are, documentation doesn't explain them.

Has anyone tried similar thing?

**Comment by miso-belica** [comment]
Hi, if you can collect verbs from the text it should be as you said. Edmundson is the method for you. Use those words as hints for the method.

Regarding the stop-words, it's not that hard to [Google them](https://en.wikipedia.org/wiki/Stop_word) 😏 

I am curious what you come with and about the results. Don't forget to let us all know 🙂

**Comment by miso-belica** [comment]
@mrx23dot did my suggestion help a bit?
