### ISSUE TITLE
A HuggingFace space for sumy

### ISSUE THREAD

**Issue by issam9** [miso-belica/sumy#183]
I'm not sure if it's okay to mention this here but I made a HuggingFace space for sumy that I think makes it easy and quick to try out the library. It is available at this link: https://huggingface.co/spaces/issam9/sumy_space

**Comment by miso-belica** [comment]
Wow, thats nice, thank you :)

**Comment by miso-belica** [comment]
https://github.com/miso-belica/sumy/commit/af5a236b45d1462e38cdff2f2abd471e9c8bbdaa
