### ISSUE TITLE
Edmundson summarization technique implementation

### ISSUE THREAD

**Issue by magic890** [miso-belica/sumy#19]
Hi,

thank you for the wonderful module!

I'm working in Scala trying to write Edmundson summarisation technique like the one used in your module, can you please give me a reference / paper / pseudo-code implementation please.

Have you got a list of academic papers as references for formulas?

**Comment by miso-belica** [comment]
Thanks. I added some info into readme. You can find more references in [my thesis](http://www.fit.vutbr.cz/study/DP/DP.php.en?id=14926) but the main content is in Slovak language.
