### ISSUE TITLE
What is the point of Docker image ?

### ISSUE THREAD

**Issue by yanna92yar** [miso-belica/sumy#193]
Hi,
Thank you @miso-belica  this is a bright work

I have a question, actually docker image would be useful not for a one single call, invoking the library just after a lot of compilation time then the image is killed;

It would be better to run a web server like Flask to persist the models / variables in memory for successive calls.

Or am I missing something ?

Thanks

**Comment by miso-belica** [comment]
Hello, docker image was created as a way to try sumy's CLI for people with little to no experience with Python without dealing with instalation of Python and related ecosystem. Currently the easiest way is to run it on huggingface but it wasn't available before and I still maintain it. Sumy is a library so if you need to build a webserver to have an API or UI it's up to you :)
