### ISSUE TITLE
Lexrank scores all the sentences the same.

### ISSUE THREAD

**Issue by acohan** [miso-belica/sumy#26]
No matter what are the sentences, the scores returned by lexrank is the same for all the sentences.
i.e. 1/count(sentences)
``lex_rank.py``
```python
file: lex_rank.py
...
[41] matrix = self._create_matrix(sentences_words, self.threshold, tf_metrics, idf_metrics)
[42] scores = self.power_method(matrix, self.epsilon)
print scores
>>> [0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329, 0.083333333333333329]
```

**Comment by Crista23** [comment]
I wanted to report the very same thing, and saw that there is already an issue about that. Has this been resolved or not yet?

**Comment by acohan** [comment]
The bug I think is in power_method function (line 128) in this module: sumy/summarizers/lex_rank.py.

Specifically, I changed line 138 to the following and now it works as expected:
``` python
138:  next_p[i] += transposed_matrix[i, j] * p_vector[j]
```

According to the paper, ```lambda_val``` should also be the square root of sum. not sum. i.e.

``` python
140: lambda_val = math.sqrt(sum((next_p[i] - p_vector[i])**2 for i in range(sentences_count)))
```

**Comment by Crista23** [comment]
Hmm.. I still get the same scores. It's also interesting that it outputs the sentences in exact order as they are in the original document:

SentenceInfo(sentence=<Sentence: Contact us!>, order=0, rating=0.16666666666666666), SentenceInfo(sentence=<Sentence: Barack Obama today was in a charity campaign where he attended official visits in Africa.>, order=1, rating=0.16666666666666666), SentenceInfo(sentence=<Sentence: His wife Michelle Obama accompanied him.>, order=2, rating=0.16666666666666666), SentenceInfo(sentence=<Sentence: Why do't you join us?>, order=3, rating=0.16666666666666666), SentenceInfo(sentence=<Sentence: Register now.>, order=4, rating=0.16666666666666666)

**Comment by miso-belica** [comment]
Hi, thanks for the reports. I hope I'll dig into this after I return from swimming pool. There is pretty hot here right now for fixing the bugs :)

**Comment by miso-belica** [comment]
Hi, this should be now resolved. I [updated power method](https://github.com/miso-belica/sumy/blob/d9d8d27987735d8068b626e32aa78f337e6811bb/sumy/summarizers/lex_rank.py#L143-L145) so it uses algorithms from numpy instead of reinventing the whell. Thanks :)

If you think this issue is not resolved, please let me know. I plan to release new version of sumy this week.

**Comment by dungtran18** [comment]
@miso-belica where is the damping factor (0.85) was said in the paper? Thanks!
