### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by PenniesEverywhere** [miso-belica/sumy#27]
Python 2.7 on Win32. Problem with UnicodeDecode requires generic handling, I suppose. Input text is plain text, so no reason for error message.

**Comment by miso-belica** [comment]
Hi, please describe minimal example, what it produces and what you think it should produce. I have no idea what is the problem from the description above. Thanks

**Comment by miso-belica** [comment]
I can't reproduce the bug. I this bug still persists please provide more info and I'll fix it :)
