### ISSUE TITLE
Sumy not correctly handling points which do not end sentences like "e.g." in english

### ISSUE THREAD

**Issue by AtomicStryker** [miso-belica/sumy#28]
Sumy is run by using a java processbuilder (essentially a command line call) to a python script, which i posted here: http://pastebin.com/9JDbPFVH. A test text exemplifying to issue can be found here: http://pastebin.com/gD65sS22

An example would be running the sumyapi.py file using arguments lex_rank, english, 3 and the provided text. The output is:

"Viral videos have become a staple of the social Web. The term refers to videos that are uploaded to video sharing sites such as YouTube, Vimeo, or Blip.tv and more or less quickly gain the attention of millions of people. Viral videos mainly contain humorous content such as bloopers in television shows (e.g. "

As is apparent, the algorithm has determined the "e.g." ends a sentence. This is not the case. The "(" infront of it has no effect, and replacing "e.g." with less formal "eg." yields the same result as well.

I've also checked against the german language in which the same construct "z.B." is correctly ignored by sumy in terms of sentence endings. I am told the python NLTK should have taken care of this. I am not nearly proficient enough with python to attempt to fix this.

**Comment by AtomicStryker** [comment]
Just to make sure i also checked with plaintext input from files or piped, it has the same defective behaviour.

**Comment by AtomicStryker** [comment]
Upon further investigation it is in fact NLTK causing the problem, and it can be fixed by adding abbrev_types parameters before tokenization. Pull request: https://github.com/miso-belica/sumy/pull/29

**Comment by Crista23** [comment]
Is it possible to give to sumy as input a list of already delimited sentences, instead of the entire plain text? In this way I could circumvent sumy to make its own sentence splits, and would be very helpful.

**Comment by miso-belica** [comment]
@Crista23 Every summarizer consumes `sumy.models.dom.ObjectDocumentModel` so if you build your own from tokenized sentences you can pass it into every summarizer. For example by this code
```python
sentences = ["You sentences", "goes here", "..."]
sentences = [Sentence(s, tokenizer) for s in sentences]  # sumy.models.dom.Sentence
paragraph = Paragraph(sentences)  # sumy.models.dom.Paragraph
dom = ObjectDocumentModel([paragraph])
summarizer(dom)

```

**Comment by miso-belica** [comment]
@AtomicStryker PR merged, thanks.

**Comment by guipaiva** [comment]
> @Crista23 Every summarizer consumes `sumy.models.dom.ObjectDocumentModel` so if you build your own from tokenized sentences you can pass it into every summarizer. For example by this code
> 
> ```python
> sentences = ["You sentences", "goes here", "..."]
> sentences = [Sentence(s, tokenizer) for s in sentences]  # sumy.models.dom.Sentence
> paragraph = Paragraph(sentences)  # sumy.models.dom.Paragraph
> dom = ObjectDocumentModel([paragraph])
> summarizer(dom)
> ```

I'm unable to do like that example. It gives me en error: 
TypeError: to_words() missing 1 required positional argument: 'sentence'
