### ISSUE TITLE
Is sumy utilising any corpus?

### ISSUE THREAD

**Issue by houmie** [miso-belica/sumy#33]
I was wondering if e.g. the brown corpus would be utilised to achieve better LSA results?
Or are the corpora only utilised for tagging?

**Comment by miso-belica** [comment]
Hi, unfortunately I don't understand you. I don't think any corpus would bring better results into LSA summarization method. This method is not trained on any corpus. Implemented LSA is unsupervised summarization method and currently there is no way how to train it on some corpus.
