### ISSUE TITLE
multiple document summarisation

### ISSUE THREAD

**Issue by myMaid** [miso-belica/sumy#38]
I don't know if this can work for multidocument summary.
I tried using a folder(where all txt fils were) but it didn't work. it worked for single document( i used lexrank and texrank) but is there a way to feed in multiple text files and get just one summary? 
Thank you

**Comment by miso-belica** [comment]
Hi, there is no support for multi-document summarization yet. You can concat documents into single file, but I don't think that's good idea.

But any PR is very welcome ;)
