### ISSUE TITLE
about KLSummarizer

### ISSUE THREAD

**Issue by duxy-me** [miso-belica/sumy#41]
There are some bugs in the tf compute. 
1. in function _compute_tf, the divide is integer divide so that all the results become 0. So i add a type convertion float() there.
 `content_word_tf = dict((k, float(v) / content_words_count) for (k, v) in content_words_freq.items())`
2. In _kl_divergence function, the w in summary_freq may not exist in doc_freq because of the filter method. Maybe we should add an 'if' before the sentence?
```python
      for w in summary_freq:
            sum_val += doc_freq[w] * math.log(doc_freq[w] / summary_freq[w])
```

**Comment by miso-belica** [comment]
Thanks, I'll dig into this later.

**Comment by miso-belica** [comment]
1. This is not an issue. I added [tests](https://github.com/miso-belica/sumy/commit/6e356501699d4e9a1d0a1644a6c732fc404fff71) for this.
2. Thanks a lot again. [fixed](https://github.com/miso-belica/sumy/commit/0d86e36efc349fb70f4c6c375799778a77c163ed)
