### ISSUE TITLE
Multi document summarization

### ISSUE THREAD

**Issue by abhigenie92** [miso-belica/sumy#42]
Hey does this package offer multi-document. If yes is there a example avialable somewhere?

**Comment by miso-belica** [comment]
Hi, currently multi-document summarization is not supported. But Pull Requests are welcome :)

**Comment by agdel1921** [comment]
from sumy.parsers.html import HtmlParser
Traceback (most recent call last):

  File "<ipython-input-11-3ba007b4cbe0>", line 1, in <module>
    from sumy.parsers.html import HtmlParser

  File "sumy.py", line 13, in <module>
    from sumy.parsers.html import HtmlParser

ImportError: No module named parsers.html

How to sove this problem. I am using MAC, python 2.7 and NLTK 3

**Comment by miso-belica** [comment]
@agdel1921 please report new issue when you have some non-open problem. Here probably your file is named `sumy.py` and should be renamed into someting else, e.g `experiment.py`.

**Comment by agdel1921** [comment]
Thank you for your prompt reply. Well I did one mistake. I have two files
with same name as sumy.py, thats why I faced the problem. Now it has been
resolved.

Thanking You
Regards
Ashutosh Gaur
M.Tech(KE), NUS
