### ISSUE TITLE
Documentation and Examples for other summarizers

### ISSUE THREAD

**Issue by gadgetsam** [miso-belica/sumy#55]
I see the documentation for the LSA summarizer and how you should use it in python. I was wondering if you could also add examples on how to use, the other types of summarization, in python?

Thanks,
Sam

**Comment by miso-belica** [comment]
Hi, what do you mean? Other summarizers are used the same way. Just replace import on the top of file.

**Comment by gadgetsam** [comment]
Hi,

When I try to run    EdmundsonSummarizer, I get a raise ValueError("Set of bonus words is empty. Please set attribute 'bonus_words' with collection of words.")
ValueError: Set of bonus words is empty. Please set attribute 'bonus_words' with collection of words.

Any help would be appreciated?
Thanks,
Sam

**Comment by miso-belica** [comment]
And is that unclear error message? Edmundson summarizer has *bonus words* and they should be set. Why did you choose Edmundson summarizer? I simply suppose user understand summarization method he uses. But it is true that Edmundson sumarizer is quite different. I'll try to update README with that.

**Comment by aburkov** [comment]
"I'll try to update README with that." said the author two years ago and never update the readme.

**Comment by amitabz** [comment]
Hi,

Can you please add use case example for Edmundson summarizer in Python. it gives the same error as above.

**Comment by traverseda** [comment]
You can see where the CLI tool initialized itself [here](https://github.com/miso-belica/sumy/blob/master/sumy/__main__.py#L120).

```python
summarizer.null_words = stop_words
summarizer.bonus_words = parser.significant_words
summarizer.stigma_words = parser.stigma_words
```
