### ISSUE TITLE
Unable to find `vcvarsall.bat` during pip install

### ISSUE THREAD

**Issue by blackfellas** [miso-belica/sumy#56]
copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Unable to find vcvarsall.bat

**Comment by miso-belica** [comment]
Hi, this is problem with lxml library. If you are on windows, try to install it with wheel of download lxml from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
