### ISSUE TITLE
Russian support

### ISSUE THREAD

**Issue by cabadsanchez** [miso-belica/sumy#57]
I've tried adding a punkt tokenizer in russian (from https://github.com/mhq/train_punkt) and a stopwords list from http://www.ranks.nl/stopwords/russian

It seems to be working fine, is this a correct approach?

**Comment by miso-belica** [comment]
If you are trying to add Russian support I think it's OK. Have you some code somewhere to see?

**Comment by cabadsanchez** [comment]
I haven't change your code. I've just copied a Russian tokenizer trained from Wikipedia articles (with this code https://github.com/mhq/train_punkt/blob/master/train_tokenizer.py) in my nltk_data folder, and the stopwords list linked above in sumy/data/stopwords.

**Comment by miso-belica** [comment]
I think it's correct approach since sumy just wraps NLTK's tokenizer/stemmer. But the stopwors are not used from NLTK, but from [custom folder](https://github.com/miso-belica/sumy/tree/dev/sumy/data/stopwords) so you should add them there.

**Comment by cabadsanchez** [comment]
Yes, there's where I put the stopwords list. Thanks!
