### ISSUE TITLE
Summarization of DOCX & PDF formats

### ISSUE THREAD

**Issue by vishalvnair** [miso-belica/sumy#6]
Hai,
First of all thanks for this wonderful module.
I have installed the sumy in my local and run the following command in my terminal 
from sumy-master folder

```
/home/dev001/projects_new/demos/sumy-master$ sumy lex-rank --length=10 --url=http://en.wikipedia.org/wiki/Automatic_summarization
```
I got the summarization text.
======================================================
Then i tried for a document summarization
i created a simple test.txt  and also a simple success.pdf file in in sumy-master folder and run the following command

```
sumy_eval edmundson  test.txt --language=english --file=http://192.168.1.86/dev001/projects_new/pivotv5/file/document/2013/09/c514e708cbbc198fc89111333d0ce53b.docx --format=docx
```

But am getting invalid syntax error . I tried with relative path to file as `--file=home/dev001/projects_new/demos/sumy-master/success.pdf`
Also the same invalid syntax error.
====================================================
Then i tried the following command.
```
sumy edmundson  --language=english --file=/home/dev001/projects_new/pivotv5/file/document/2013/09/c514e708cbbc198fc89111333d0ce53b.docx --format=docx
```
I am getting error as `UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 16: invalid start byte`

Please help me. Kindly give me an example for document summarization.
It would a great relief for me.

Thanks in advance

**Comment by miso-belica** [comment]
@vishalvnair what about the parser for PDF, DOCX documents? Did you succeed?
