### ISSUE TITLE
sumy_eval

### ISSUE THREAD

**Issue by kamikater34** [miso-belica/sumy#65]
Hi,
pretty new to Python and the field of automated summarization but your sumy was a great introduction.

Currently I still lack a bit of usage/info on sum_eval - can you shed some light on this Topic and proper usage? (didn't really got it from sum_eval --help)

**Comment by HerocypheR** [comment]
@kamikater34 maybe i can explain something about it. 

U should use like that syntax :

sumy_eval lsa C:\Users\zer03\a.txt --file=C:\Users\zer03\b.txt --format=plaintext

(sumy_eval) + ("lsa" or "lex-rank"..etc.) + (referencee summary txt path) + ( if ur candidate summary in local txt : --file <path>   or if ur txt in url --url:<urladres>) + (--format= "plaintext" or "html" ).
..

its work great on command prompt python. But when i try to use on ide(Anaconda-Spyder) , i get error.

**Comment by miso-belica** [comment]
@kamikater34 It's quite simple. You just need to have reference summary to evaluate summarization method (result of the merhod). This reference summary may be written by you or another summarization system. The you pass the reference summary to the `sumy_eval` and sumy creates new summary and combares it with reference summary. 

This assumes your reference summary has very good quality and mostly evaluation is done by creating more reference summaries and evaluating for all of them to make sure evaluation is not just opinion of one author about the summary quality.
