### ISSUE TITLE
Sumy running the sample not working

### ISSUE THREAD

**Issue by varunm100** [miso-belica/sumy#68]
I ran the program you put on github and I got a few errors. I checked if sumy was installed and it was.

Link to the screenshot

![sumy prob](https://cloud.githubusercontent.com/assets/19439575/19373533/368e0b92-91e2-11e6-8879-f5c787fc963a.png)

**Comment by miso-belica** [comment]
Hi, it's strange I tested it on my machine with the same problem, but after I run `pip uninstall sumy && pip install -U sumy` it works fine. Try it please and let me know.

**Comment by Lyngby** [comment]
look at the error message. It tells you that you have no module named sumy.parsers.html. Did you remember to install the sumy package using pip before you ran the script?

**Comment by varunm100** [comment]
yes I checked in the pip list

**Comment by miso-belica** [comment]
So does the `pip uninstall sumy && pip install -U sumy` work foy you or not?

**Comment by varunm100** [comment]
I fixed my problem by reinstalling pyaudio
