### ISSUE TITLE
Summarising a 'narrative' rather than a well-formed topic

### ISSUE THREAD

**Issue by OmegaPhil** [miso-belica/sumy#70]
Not a problem but more a cheeky question to leech some of your knowledge - playing around with this text summarisation, it appears to be able to deal OK with something like a wiki article, but falls apart when given a forum thread - I assume its the difference between an article which is a 100% 'final understanding' of one or more topics, rather than a forum thread where understanding builds hopefully to some sort of conclusion (so presumably it has to actually understand what is being talked about to summarise), and in a much looser format.

I'm guessing actual understanding of what is discussed and then summarising is light years beyond the current capabiliy of sumy and in general libre text summarisation software - is this correct?

Thanks

**Comment by miso-belica** [comment]
@OmegaPhil Yes you are right. Of course it depends on used summary method and many other aspects, but sumy is intended to summarize text of certain topic(s) not threads with many different comments and I didn't test it for such a task.

But still I don't think it is light years beyound sumy's capabilities. It's just about doing some tests and research and maybe tweak some parameters of summarizators :) Or just about implementing new one that are able to follow discussion in thread-like texts.
