### ISSUE TITLE
How do you test the summarizer?

### ISSUE THREAD

**Issue by amirouche** [miso-belica/sumy#76]
Do you use a particular dataset?

**Comment by miso-belica** [comment]
@amirouche Hi, I have unit tests in place but from what I understand you are asking on "testing" in meaning of summarizer evaluation, right?

Sumy is not in active development for 2 years now. I am fixing issues when I can, accept PRs but I am not adding new features/summarizes, nor improving summarizers. In the time I was building this lib I have used my custom datasets with target to czech language. Not sure if I have these datasets somewhere but don't think they are interesting for someone. I also tried some publich english datasets to just make sure I am building usefull lib, but the results were nothing extra too. Compared with other extractive summarizers sumy is something in the middle in terms of summary quality.
