### ISSUE TITLE
GAE ready

### ISSUE THREAD

**Issue by hnchan** [miso-belica/sumy#80]
Can we make it be GAE ready? When I execute under GAE, it shows the following error.

```
mary/lib/nltk/tag/hunpos.py", line 16, in <module>
    from subprocess import Popen, PIPE
ImportError: cannot import name Popen

```

**Comment by miso-belica** [comment]
Hi, sorry, but without knowing what are you executing I can't help you. Also it seems that you have problem with some part of NLTK library from the stacktrace and that is something out of the scope of this library. Maybe if you can provide some usefull info about your problem I can help you.

I guess you mean Google App Engine by GAE.

**Comment by hnchan** [comment]
Yes, it should be the error from nltk and GAE means Google App Engine. Let me try to search can I fix it and will update here if I got some info.

**Comment by miso-belica** [comment]
@hnchan 
1. So have you found the fix for this? 
2. Is this still an issue for you? 
3. Do you still think it's sumy's issue?
4. If it's sumy's issue can you provide some minimal example that is not working?

**Comment by hnchan** [comment]
1. Haven't.
2. Yes.
3. No. it is just nltk library issue which won't support GAE. When it execute this line, /lib/nltk/tag/hunpos.py", line 16, in <module>, it failed.
4. I am thinking to give up GAE standard env and use flexible env which allows us to create sub-process, so it may solve this problem

**Comment by miso-belica** [comment]
Closing this as not related to sumy and wish you good luck :)
