### ISSUE TITLE
question: LexRank does not work when the number of sentences is smaller than 20

### ISSUE THREAD

**Issue by elvislili** [miso-belica/sumy#82]
I have tried to use the LexRank algorithm to summarize articles.  However, it does not work when the number of sentences of the article is very short, such as below 20.  It only extracts the sentences according to the order of the article and makes those sentences becoming the summary.

**Comment by miso-belica** [comment]
Hi, can you provide me example article and how do you use sumy?

**Comment by elvislili** [comment]
I have figured it out.  I misunderstood the mechanisms of LexRank.  I am so sorry to ask such a silly question.  Anyway, thank you for developing Sumy!!
