### ISSUE TITLE
does it  support chinese?

### ISSUE THREAD

**Issue by mickelfeng** [miso-belica/sumy#83]
I tried to set the variable "LANGUAGE = "chinese"" ,but it does not work, gives error.

**Comment by miso-belica** [comment]
Hi, currently sumy does not support chinese language. IMHO should be done similar way as in https://github.com/miso-belica/sumy/pull/79. Feel free to send PR to add chinese support :)

**Comment by miso-belica** [comment]
@astropeak added support for chinese in https://github.com/miso-belica/sumy/pull/93 :)
