### ISSUE TITLE
How to summarize .txt files.

### ISSUE THREAD

**Issue by shavid** [miso-belica/sumy#9]
Hi,

I've had a mess around with Sumy and it seems to be perfect for the small project I've been working on. However I've only been able to work with URL's. What code would i need to implement to summarize a block of text. Either saved in a variable or loaded from a .txt file.

Regards.

**Comment by ravikant987** [comment]
Sir thanks for share this code.
please tell me, i want to take a database text directly with query then what is the procedure to write  code for that database data to be summarize in spite of 
parser = PlaintextParser.from_file("document.txt", Tokenizer(LANGUAGE))
