### ISSUE TITLE
Cannot import name PlaintextParser

### ISSUE THREAD

**Issue by hernhern** [miso-belica/sumy#90]
from sumy.parsers.html import PlaintextParser

ImportError: cannot import name PlaintextParser (or Tokenizer etc)

I've already tried pip uninstall and reinstalling, no, my script name is not sumy.

Python 2.7, on mac. Thanks for helping!

**Comment by miso-belica** [comment]
If name of your script is not `sumy.py` I have no idea. Sorry. Try `pip2 freeze | grep sumy`. If the package is there, try to look at source codes placed in directory with installed modules.

**Comment by miso-belica** [comment]
@hernhern Did you find the solution for your problem? Where was the catch?

**Comment by miso-belica** [comment]
Guess @hernhern is able to import parser now. Closing, because it works for me and seems nobody else has the same issue.
