### ISSUE TITLE
Support Chinese document

### ISSUE THREAD

**Issue by astropeak** [miso-belica/sumy#92]
Hello,

I tested the software and find it not support Chinese. Do you have any plan to support Chinese document? Thank you!

BR,
Astropeak

**Comment by miso-belica** [comment]
Yes there was https://github.com/miso-belica/sumy/issues/83#issuecomment-280641854 for this already. I don't plan to add support but if you need it I would appreciate it and can help you with it. Also https://github.com/miso-belica/sumy/pull/79 is good inspiration for you :)

**Comment by astropeak** [comment]
I will work on this. The solution for Chinese should be much similar to Japanese.

**Comment by miso-belica** [comment]
@astropeak added support in https://github.com/miso-belica/sumy/pull/93 Thanks again
