### ISSUE TITLE
Help with creating parser object from pandas dataframe

### ISSUE THREAD

**Issue by vineysindhu** [miso-belica/sumy#94]
@miso-belica 

Hi Miso

I am new to python. I am trying to summarize data which I have in mysql table. I  am reading that data in pandas dataframe and creating a list from the column which needs to be summarized. Can you please help me on how to create a object from pandas dataframe column that is similar to below object.
`parser = PlaintextParser.from_file(r"....\document.txt", Tokenizer(LANGUAGE))`
which can be passed as parameter to summarizer as  `parser.document`.

Also if you can give me an example on how to use sum_eval in IDE, rather than command line, that would be helpful.

Regards
Viney Sindhu

**Comment by miso-belica** [comment]
Hi, from what I can see path to the file `....\document.txt` seems very suspicious and that's probably the issue. Without stacktrace or something else to test I can't help more.

**Comment by vineysindhu** [comment]
Thank you for your quick response. That was just an example, not an actual path. My actual data which I want to summarize is in pandas dataframe. I want to summarize data from pandas dataframe column, rahter then a text file or HTML file.

**Comment by vineysindhu** [comment]
I tried to write data from pandas dataframe to a text file and then summarize it. It worked fine, however I want to remove that step of writing data to a text file and then reading it, because it is adding input and output step which inturn increase the running time of the program.

**Comment by miso-belica** [comment]
And `PlaintextParser.from_string(frame["text"], Tokenizer(LANGUAGE))` does not work? As I said. If you don't give me the code that is not working with the stacktrace you get, I can't help you.

**Comment by vineysindhu** [comment]
parser = PlaintextParser.from_file(agr_corn['post_message'], Tokenizer(LANGUAGE))

parser = PlaintextParser.from_file(agr_corn['post_message'], Tokenizer(LANGUAGE))
Traceback (most recent call last):

  File "<ipython-input-79-067a2ded8e15>", line 1, in <module>
    parser = PlaintextParser.from_file(agr_corn['post_message'], Tokenizer(LANGUAGE))

  File "C:\Users\viney.sindhu\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumy\parsers\plaintext.py", line 34, in from_file
    with open(file_path) as file:

TypeError: expected str, bytes or os.PathLike object, not Series

**Comment by miso-belica** [comment]
I did not work with Pandas much, but you need to extract line from Series object. Something like

```python
for index, row in agr_corn.iterrows():
  parser = PlaintextParser.from_string(row['post_message'], Tokenizer(LANGUAGE))
  # pass parser to sumy to sumarize text
```

IMHO this is question to some pandas forum or other general programming forum about python. You should read documentation and just extract text for every row and then summarize it. Hope it was helpful.

**Comment by vineysindhu** [comment]
Thanks Miso.
