### ISSUE TITLE
Not all german sentences split correctly

### ISSUE THREAD

**Issue by workflowsguy** [miso-belica/sumy#97]
When throwing various german texts at `sumy`, I noticed that some sentence boundaries are not detected.

This shows e.g. in the following summary output:

`»Die Übergabe fand immer bar in der Hauptkasse statt.« Am 31. August bzw. 21. November 2012 holte sie 7000 bzw. 7500 Euro ab.`

This should actually be two sentences, split at the `.«` I also noticed some other cases where typographical quotes are not handled correctly.

Also, the following sentence from the original text:

`Dort ging es um ca. 600 Millionen Euro.«`

shows up in the summary as

`Dort ging es um ca.`

(the command line used was 
`sumy lex-rank --lang=german --file="/Volumes/Public/bearbeiten/Texte/benennen Buch/German.txt"`)

**Comment by miso-belica** [comment]
Hi, sumy is using NLTK framework to split sentences. If you know some better library to do this feel free to contribute to sumy :) Or you can just create your own tokenizer and use it with sumy. It's [simple class](https://github.com/miso-belica/sumy/blob/dev/sumy/nlp/tokenizers.py#L37) with two methods `to_sentences` and `to_words`.

**Comment by workflowsguy** [comment]
Hello,

as I also encounter this issue in other tools that build upon NLTK, I think the better solution is to have this addressed in NLTK itself. So I have opened a request there; let's see what the view of the NLTK people is.

**Comment by miso-belica** [comment]
Thanks :) https://github.com/nltk/nltk/issues/1903
