### ISSUE TITLE
Why can't import sumy by ide

### ISSUE THREAD

**Issue by 258513813** [miso-belica/sumy#98]
In ide sush as ： ecplise、Pycharm occur the problem：
from sumy.parsers.html import HtmlParser
error： ModuleNotFoundError: No module named 'sumy.parsers'; 'sumy' is not a package

 but in cmd，  from sumy.parsers.html import HtmlParser is work well

**Comment by miso-belica** [comment]
To be honest, I have no idea why it does not work. I am happy user of Intellij IDEA and it is fine for me. Maybe you need to set some PATH variable or so. But this is more IDE specific problem than issue in sumy so I am closing this issue. Hope you'll find the solution for your problem :)

**Comment by 258513813** [comment]
Thanks for your answer， I can't understand is that others lib import and were worked well， just sumy， so  ...
