### ISSUE TITLE
[chinese] chinese paragraph splitlines error

### ISSUE THREAD

**Issue by smileboywtu** [miso-belica/sumy#99]
chinese long text may not use \r\n, may be some stop word in a paragraph, but it a new line, in chinese splitline means split paragraph, so need customer way for each language to implement splitlines.

**Comment by miso-belica** [comment]
Sorry, but I don't understand where is the problem and what is expected behavior. Can you please write an example with current behavior and expected one and descibe them? Thanks

**Comment by smileboywtu** [comment]
https://zhidao.baidu.com/question/554645964292309132.html?fr=iks&word=6.%D6%D0%B9%FA%C0%FA%CA%B7%C9%CF%D6%F8%C3%FB%B5%C4%C1%CF%BE%D9%D6%C6%B6%C8%BF%AA%CA%BC%D3%DA%C4%C4%B8%F6%B3%AF%B4%FA%3F&ie=gbk

**Comment by smileboywtu** [comment]
i parse the words inside this site, but the `parser.document.sentences` is `()` empty , so how can i normalize the text?

**Comment by smileboywtu** [comment]
https://docs.python.org/3/library/stdtypes.html

`isupper` function will return `True` for chinese paragraph make all sentence in heading, so why?

i know how to fix it , but can't know why maybe a bug in python3

**Comment by miso-belica** [comment]
Sorry, but it seems this is not related to sumy. I know nothing about Chinese text but seems like Python is not handling it correctly. It's no surprise. The most of the text utils in the programming world does not count with Chinese. I had similar experience with Arabic text and I needed special libraries/code to work properly with it. I suggest you to search the internet for "how to process Chinese text in Python". I can't help you more here IMHO.

If you can some suggestions how to fix the behavior in sumy, feel free to write the tips here or send a PR :) Nice weekend
